export const CATS_GET_SUCCESS = "CATS_GET_SUCCESS";
export const CATS_GET_FAILURE = "CATS_GET_FAILURE";

export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_FAILURE = "CATEGORIES_GET_FAILURE";
